### PR TITLE
Update header

### PR DESCRIPTION
**Pull request by Alex-Cremers**
Updated header to 2018 (including license), and deadlines for the first two weeks of homework.

### CODE REVIEW

**Comment by bacor** [comment]
@Alex-Cremers, because of some conflicts I've updated your changes manually and recompiled all PDFs with the new header, so I'm closing this PR.

Also good to know: I moved the practice exercises to the `practice` folder.

BTW, don't you have push access to this repo? (Then you don't have to fork it)

**Comment by Alex-Cremers** [comment]
Thanks! Apparently I don't have push access to the homework folder (I did
seem to have access to the Lecture one though). Sorry I didn't pay
attention to the practice being in a different folder!
A

**Comment by bacor** [comment]
Hmm... Maybe we can check that tomorrow.

**Comment by Alex-Cremers** [comment]
Don't worry, no emergency!

2018-02-06 18:53 GMT+01:00 Bas <notifications@github.com>:

**Pull request closed without merging**
